Repository AOMediaCodec/iamf, pull requests merged in 2023-06, with the labels that each got.

#430 For signed demixing matrix of ambisonics config
  index.bs
Labels: bug

#431 Fix #421, add default value for demixing and recon gain
  index.bs
Labels: bug

#434 Updated recon_gain operations
  images/Smoothing Scheme of Recon Gain.png
  index.bs
Labels: bug

#435 Fix #410, clarified usage of demixing and recon gain
  index.bs
Labels: bug

#455 Fix #443
  index.bs
Labels: editorial

#456 Fix #444
  index.bs
Labels: editorial

#427 Fix #402, loudness for Mono
  index.bs
Labels: bug

#439 Issue #384: Clarify Opus output sample rate should be 48 kHz (try 2)
  index.bs
Labels: editorial

#426 Fix #399, Codec Config Improvement
  index.bs
Labels: editorial

#440 Fix #412, IAMF Generation Process is marked as Informative and some s…
  index.bs
Labels: editorial

#466 Fix #465, 'roll' sample group clarification
  index.bs
Labels: bug

#458 Fix #95, Introduction Improvement
  images/Hypothetical IAMF Architecture.png
  images/IAMF Timing Model.png
  index.bs
Labels: editorial

#481 Fix #473, Section 2 OBU Syntax Improvement
  index.bs
Labels: editorial

#482 Fix #474, Section 3 Profiles Improvement
  index.bs
Labels: editorial

#483 Fix #475, Section 4 Standalone IAMF Improvement
  index.bs
Labels: editorial

#484 Fix #476, Section 5 ISOBMFF IAMF Encapsulation Improvement
  index.bs
Labels: editorial

#486 Fix #479, Annex Improvement
  index.bs
Labels: editorial

#533 Fix #518, Clarify use of AudioSampleEntry channelcount and samplereate
  index.bs
Labels: new_bitstream_required

#529 Fix #513, Order of fields in ParamDefinition
  index.bs
Labels: new_bitstream_required

#534 Fix #519, Optional boxes in sample entry
  index.bs
Labels: new_bitstream_required

#526 Fix #525, to fix convention for string
  index.bs
Labels: new_bitstream_required

#528 Fix #527, to support extension of Audio Element OBU in terms of new param definition and audio element type
  index.bs
Labels: new_bitstream_required

#535 Fix #530, Consider an extension of loudness info()
  index.bs
Labels: new_bitstream_required

#537 Fix #532, to consider an extension of PBO
  index.bs
Labels: new_bitstream_required

#500 Fix #492: Increase number of reserved OBU types by reducing
  index.bs
Labels: new_bitstream_required

#509 Fix #491, updating rendering_config()
  index.bs
Labels: new_bitstream_required

#543 Fix #523, extra bytes at the end of an OBU
  index.bs
Labels: new_bitstream_required

#503 Fix #493, Clarification on extension header
  index.bs
Labels: new_bitstream_required

#480 Fix #472, Section1 Introduction - Clarified the meaning of mixed audio element
  images/Hypothetical IAMF Architecture.png
  images/IAMF Timing Model.png
  index.bs
Labels: editorial

#504 Fix Bezier: when alpha==0
  index.bs
Labels: bug
